name: Terraform apply infra change

on:
push:
branches: ["main"]
workflow_dispatch:

permissions:
id-token: write
contents: read

jobs:
dev:
	name: dev
	needs: [[]]
	runs-on: ubuntu-latest
	steps:
	 - run: echo "running dev stage"

dev/sample:
	uses: ./.github/workflows/site-cd-workflow.yml
	with:
		working-directory: dev/dev/sample
	secrets: inherit
	needs: [dev]

qa:
	name: qa
	needs: [[dev/sample]]
	runs-on: ubuntu-latest
	steps:
	 - run: echo "running qa stage"
